### ISSUE TITLE
Add hardware wallet support

### ISSUE THREAD

**Issue by john-light** [blockstack/cli-blockstack#39]
Currently, users have to paste their unencrypted seed phrase and private keys directly into their terminal when using Blockstack CLI. Ideally users would be able to keep their keys in cold storage while retaining the ability to conveniently use the CLI. A hardware wallet offers a nice middle-ground between offline key storage and online availability. I would like to see hardware wallet support added to the CLI so users can use the CLI without having to expose their seeds/private keys on an online computer.

**Comment by jcnelson** [comment]
Per the README, this tool is meant for developers -- specifically, developers who need a lightweight shell wrapper around methods in blockstack.js.  This tool isn't trying to be a wallet, for the same reason that blockstack.js isn't trying to be a wallet.

**Comment by john-light** [comment]
@jcnelson there are a few important name operations that are currently only accessible via the CLI, for example transferring a name or creating a new namespace. In both cases I think there are security and UX benefits to enabling direct hardware wallet support rather than forcing users to either enter their seed phrase directly into the CLI commands or first transferring BTC from a hardware wallet to a hot wallet then performing the necessary commands.

The alternative is moving these operations to the app layer and exposing a hardware interface at that layer but currently, to the best of my knowledge, such apps do not exist, so the CLI is the only available option.

**Comment by jcnelson** [comment]
Both of these things can be true: there are certain operations that right now can only be done in the CLI, and the CLI is not meant to be a wallet.

The solution would be to modify the user-facing software (i.e. the authenticator, the wallet) to be able to do all the name operations the CLI can currently do, since the user-facing software is meant to provide a safe, easy way to do them.  Please open issues for this on either [1] or [2].

[1] https://github.com/blockstack/stacks-wallet
[2] https://github.com/blockstack/blockstack-browser

**Comment by john-light** [comment]
Fair enough, thank you for taking the time to review the issue and respond :+1:
